### ISSUE TITLE
¿Cómo se ejecuta?

### ISSUE THREAD

**Issue by pcha** [jcodagnone/inmuebles#1]
Me gusta mucho la iniciativa, me gustaría revivirla, ¿cómo hay que hacer para acceder a la aplicación?

**Comment by jcodagnone** [comment]
Hola Pablo,

Gracias por el interés. Es cierto el archivo README está escaso de información, y faltó sistematizar la instalación de librerías necesarias. Fue un experimento que hice al menos una década atrás cuando estaba buscando una oficina y quería geo-referenciar algunos de sus datos.

El archivo geocorder.py no va a funcionar porque usaba el geocoder que había implementado para flof.com.ar (que no está mas en linea). 
Consistía de un scrapper que tomaba la importaba la informacion, y una web para manejar los lugares y verlos en el mapa (ejecutando ./web.py).

```
inmuebles $ ./scrapper.py 784612
                      the_geom: -58.451534 -34.588055
               Código de ficha: AR - AE42588
              Superficie total: 140 m2
                        Precio: $ 1200
        Condición del inmueble: --
                    Antigüedad: 20 años
                     Operación: Alquiler ofrecido
             Tipo de propiedad: Locales Comerciales, Oficinas y Consultorios
                       Visitas: 136
          Fecha de publicación: 08/10/2006
                     Ubicación: Bs. As. Capital Federal Capital Federal Villa Crespo FOREST, AV. 300
             Superficie propia: --
 
```

Hoy en día seguramente Properati te lo permite hacer seguramente.
